name: yutori server

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCE_INSTANCE: instance-01	  
  GCE_INSTANCE_ZONE: asia-northeast3-a	
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: GCP connect
      uses: google-github-actions/setup-gcloud@master
      with: 
        service_account_key: ${{ secrets.GCP_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
